### ISSUE TITLE
Windows download base image error

### ISSUE THREAD

**Issue by xcv58** [ops-class/vagrant#1]
The Vagrant has embedded `CURL.EXE`. The `CURL.EXE` requires `MSVCR100.dll`. But some Windows OS versions don't have `MSVCR100.dll`.

However, the Vagrant can't catch the missing `MSVCR100.dll` error:
`The Program can't start becuase MSVCR100.dll is missing from your computer. Try reinstalling the program to fix this problem.`

It just shows error happen with empty error message.
# To fix this:

Download `MSVCR100.dll` from http://fix4dll.com/msvcr100_dll based on your OS.

Copy downloaded `MSVCR100.dll` to `C:\Windows\System` or `C:\Windows\System32\` or `C:\Windows\SysWOW64\` based on your System version 32-bit/64-bit.

Video tutorial can be found: https://www.youtube.com/watch?v=6GZH_zObpmg

**Comment by gchallen** [comment]
What are we using curl for?

**Comment by xcv58** [comment]
To get the base image.
