### ISSUE TITLE
sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by FrankSzn** [ops-class/vagrant#11]
After successfully install the vagrantfile, each time I type vagrant up. It will give me the error.
"
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -f

Stdout from the command:

Stderr from the command:

sudo: no tty present and no askpass program specified
"
So now I always  have to type the sudo to get the permission to make some commands work
Do I need to rewrite the /etc/sudoers for the following assignment

**Comment by gchallen** [comment]
Not sure what's going on here. Can you try with the new Vagrantfile?
