### ISSUE TITLE
ssh user incorrect in latest vagrant/virtualbox install

### ISSUE THREAD

**Issue by roniburd** [ops-class/vagrant#12]
It seems like the Vagrant file is using trinity as the user to log in, but my vagrant installation required 'vagrant' as the user

**Comment by jtdroste** [comment]
That means when you ran `vagrant up`, it somehow failed.  During provisioning (which happens during `vagrant up`), the user trinity is automatically created, if it doesn't exist.

Run `vagrant destroy` then `vagrant up`, and things should be good.
